source 'https://rubygems.org'

# Private gem registry for language-operator SDK
source 'https://git.theryans.io/api/packages/language-operator/rubygems' do
  gem 'language-operator', '~> 0.1.5'
end

# Email functionality
gem 'mail', '~> 2.8'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
