source 'https://rubygems.org'

gem 'language-operator', '~> 0.1.30'

# Email functionality
gem 'mail', '~> 2.8'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
